# Generated by Django 4.2.23 on 2025-06-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('occasion', models.CharField(choices=[('FALL', 'Fall'), ('BEST_SELLERS', 'Best Sellers'), ('THANKSGIVING', 'Thanksgiving'), ('PLANT', 'Plant')], max_length=50)),
                ('color', models.CharField(choices=[('WHITE', 'White'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('RED', 'Red'), ('YELLOW', 'Yellow')], max_length=50)),
                ('price', models.IntegerField()),
                ('imageUrl', models.URLField()),
                ('imageUrlSecondary', models.URLField()),
                ('description', models.CharField(max_length=1000)),
                ('amountInStock', models.IntegerField()),
            ],
        ),
    ]
