# Generated by Django 5.2.3 on 2025-06-28 18:20

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('imageUrl', models.URLField()),
                ('amountInStock', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='flower',
            name='color',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='imageUrlSecondary',
        ),
        migrations.AddField(
            model_name='flower',
            name='collection',
            field=models.CharField(choices=[('BURLAP_WRAPPED', 'Burlap Wrapped'), ('VASE_VASE_BABY', 'Vase, Vase Baby'), ('FREE_SHIP_SHOP', 'Free Ship Shop'), ('OUR_FAVORITES', 'Our Favorites'), ('BIG_BOX_SHOP', 'Big Box Shop'), ('WITH_HEART', 'With Heart'), ('PET_FRIENDLY', 'Pet Friendly'), ('PLANTS', 'Plants'), ('WREATHS', 'Wreaths')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flower',
            name='deliveryLeadTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flower',
            name='details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='flower',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='flower',
            name='imageUrls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='flower',
            name='isSingleVariety',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='occasion',
            field=models.CharField(choices=[('ANNIVERSARY', 'Anniversary'), ('BIRTHDAY', 'Birthday'), ('CONGRATULATIONS', 'Congratulations'), ('HOUSEWARMING', 'Housewarming'), ('JUST_BECAUSE', 'Just Because'), ('SYMPATHY', 'Sympathy'), ('THANK_YOU', 'Thank You')], max_length=50),
        ),
    ]
