# Generated by Django 5.2.3 on 2025-06-29 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0002_addonitem_remove_flower_color_remove_flower_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonitem',
            name='imageUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='flower',
            name='imageUrls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
    ]
