# Generated by Django 5.2.3 on 2025-06-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0003_alter_addonitem_imageurl_alter_flower_imageurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='occasion',
            field=models.CharField(choices=[('ANNIVERSARY', 'Anniversary'), ('BIRTHDAY', 'Birthday'), ('CONGRATULATIONS', 'Congratulations'), ('HOUSEWARMING', 'Housewarming'), ('JUST_BECAUSE', 'Just Because'), ('SYMPATHY', 'Sympathy'), ('THANK_YOU', 'Thank You')], max_length=50, null=True),
        ),
    ]
