# Generated by Django 5.2.3 on 2025-06-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0004_alter_flower_occasion'),
    ]

    operations = [
      migrations.RunSQL(
            """
            ALTER TABLE bloom_flower
            ALTER COLUMN details TYPE jsonb
            USING to_jsonb(details);
            """
        ),
            migrations.RunSQL(
            """
            ALTER TABLE bloom_flower
            ALTER COLUMN "imageUrls" TYPE jsonb
            USING to_jsonb("imageUrls");
            """,
        )
    ]
