# Generated by Django 5.2.3 on 2025-06-29 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0005_alter_flower_details_alter_flower_imageurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addonitem',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='isSingleVariety',
            new_name='is_single_variety',
        ),
        migrations.RemoveField(
            model_name='addonitem',
            name='amountInStock',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='amountInStock',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='deliveryLeadTime',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='imageUrls',
        ),
        migrations.AddField(
            model_name='addonitem',
            name='amount_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flower',
            name='amount_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flower',
            name='delivery_lead_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flower',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='flower',
            name='pet_safe',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='flower',
            name='type',
            field=models.CharField(choices=[('ALSTROEMERIA', 'Alstroemeria'), ('ANEMONES', 'Anemones'), ('DAISIES', 'Daisies'), ('HYDRANGEA', 'Hydrangea'), ('LILIES', 'Lilies'), ('PEONIES', 'Peonies'), ('RANUNCULUS', 'Ranunculus'), ('ROSES', 'Roses'), ('ROSELILIES', 'Roselilies'), ('SPECIALTY_GARDEN_ROSES', 'Specialty Garden Roses'), ('SUNFLOWERS', 'Sunflowers')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addonitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addonitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flower',
            name='details',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='flower',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
