# Generated by Django 5.2.3 on 2025-06-29 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0006_rename_imageurl_addonitem_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='collection',
            field=models.CharField(blank=True, choices=[('BURLAP_WRAPPED', 'Burlap Wrapped'), ('VASE_VASE_BABY', 'Vase, Vase Baby'), ('FREE_SHIP_SHOP', 'Free Ship Shop'), ('OUR_FAVORITES', 'Our Favorites'), ('BIG_BOX_SHOP', 'Big Box Shop'), ('WITH_HEART', 'With Heart'), ('PET_FRIENDLY', 'Pet Friendly'), ('PLANTS', 'Plants'), ('WREATHS', 'Wreaths')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='flower',
            name='occasion',
            field=models.CharField(blank=True, choices=[('ANNIVERSARY', 'Anniversary'), ('BIRTHDAY', 'Birthday'), ('CONGRATULATIONS', 'Congratulations'), ('HOUSEWARMING', 'Housewarming'), ('JUST_BECAUSE', 'Just Because'), ('SYMPATHY', 'Sympathy'), ('THANK_YOU', 'Thank You')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='pet_safe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='type',
            field=models.CharField(blank=True, choices=[('ALSTROEMERIA', 'Alstroemeria'), ('ANEMONES', 'Anemones'), ('DAISIES', 'Daisies'), ('HYDRANGEA', 'Hydrangea'), ('LILIES', 'Lilies'), ('PEONIES', 'Peonies'), ('RANUNCULUS', 'Ranunculus'), ('ROSES', 'Roses'), ('ROSELILIES', 'Roselilies'), ('SPECIALTY_GARDEN_ROSES', 'Specialty Garden Roses'), ('SUNFLOWERS', 'Sunflowers')], max_length=50, null=True),
        ),
    ]
